# Generated by Django 4.0 on 2023-03-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mlmodelinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
