# Generated by Django 4.0 on 2023-03-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_mlmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodelinput',
            name='attribute',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
