# Generated by Django 4.0 on 2023-03-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_mlmodelinput_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodelinput',
            name='input_type',
            field=models.CharField(choices=[('text', 'str'), ('checkbox', 'checkbox'), ('number', 'float'), ('file', 'File'), ('image', 'Image')], default='number', max_length=100),
        ),
    ]
