# Generated by Django 4.0 on 2023-03-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_mlmodelinput_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodelinput',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='home.mlmodel'),
        ),
    ]
