# Generated by Django 4.0 on 2023-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_mlmodelinput_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodelinput',
            name='input_type',
            field=models.CharField(choices=[('str', 'text'), ('checkbox', 'checkbox'), ('number', 'float'), ('file', 'file'), ('image', 'image')], default='float', max_length=100),
        ),
    ]
