# Generated by Django 4.0 on 2023-03-13 10:46

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_mlmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to=home.models.user_directory_path),
        ),
    ]
