# Generated by Django 4.0 on 2023-03-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_mlmodel_model_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='output',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
