# Generated by Django 4.0 on 2023-03-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_mlmodel_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodelinput',
            name='input_type',
            field=models.CharField(choices=[('text', 'str'), ('checkbox', 'checkbox'), ('number', 'float'), ('number', 'int'), ('file', 'file'), ('image', 'image')], default='float', max_length=100),
        ),
    ]
